@startuml

' начальные условия
' авторизованный пользователь видит иконку с приложением


start

:пользователь нажимает на иконку приложения;
if (ошибка загрузки?) then (нет)

    :отображается меню приложения;
    :пользователь нажимает на кнопку Данные о здорове;
    if (ошибка загрузки?) then (нет)
        :пользоваетль просматривает раздел Данные о здорове;
    else (да)
        :отображается модальное окно с текстом ошибки;
        :пользователь нажимает на крестик в модальном окне;


    endif

else (да)
    :отображается модальное окно с текстом ошибки;
    :пользователь нажимает на крестик в модальном окне;



endif

:приложение закрывается;

stop

@enduml
